<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1538277907099" stop="1538277907304">
  <name>test_allure</name>
  <labels/>
  <test-cases>
    <test-case start="1538277907099" status="passed" stop="1538277907115">
      <name>Test.test01</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7192-MainThread"/>
        <label name="host" value="DESKTOP-E9B9154"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps>
        <step start="1538277907114" status="passed" stop="1538277907114">
          <name>执行学院新增操作</name>
          <title>执行学院新增操作</title>
          <attachments/>
          <steps/>
        </step>
      </steps>
    </test-case>
    <test-case start="1538277907117" status="failed" stop="1538277907216">
      <name>Test.test02</name>
      <failure>
        <message>AssertionError: assert False</message>
        <stack-trace>self = &lt;test_allure.Test object at 0x0000017598AD72B0&gt;

    @allure.step("执行学院新增操作")
    @pytest.allure.severity(pytest.allure.severity_level.BLOCKER)
    def test02(self):
        allure.attach("断言开始", "学院是否更新成功")
        print("执行学院更新操作")
        allure.attach("断言结束", "更新成功")
&gt;       assert False
E       assert False

Scripts\test_allure.py:17: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="blocker"/>
        <label name="thread" value="7192-MainThread"/>
        <label name="host" value="DESKTOP-E9B9154"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps>
        <step start="1538277907117" status="failed" stop="1538277907134">
          <name>执行学院新增操作</name>
          <title>执行学院新增操作</title>
          <attachments>
            <attachment source="4cf0cf72-4ffa-4c97-b2b5-065f81a3a244-attachment.txt" title="断言开始" type="text/plain"/>
            <attachment source="1d8b16ca-2693-4331-8ef1-152ee9bee428-attachment.txt" title="断言结束" type="text/plain"/>
          </attachments>
          <steps/>
        </step>
        <step start="1538277907209" status="failed" stop="1538277907209">
          <name>执行学院新增操作</name>
          <title>执行学院新增操作</title>
          <attachments>
            <attachment source="8a253cc4-3b25-440c-b9cb-151b2835bd78-attachment.txt" title="断言开始" type="text/plain"/>
            <attachment source="655d6ed1-b8da-4608-8991-8dfed9ef040f-attachment.txt" title="断言结束" type="text/plain"/>
          </attachments>
          <steps/>
        </step>
      </steps>
    </test-case>
    <test-case start="1538277907275" status="failed" stop="1538277907304">
      <name>Test.test03</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_allure.Test object at 0x0000017598AF9EB8&gt;

    @pytest.allure.severity(pytest.allure.severity_level.CRITICAL)
    def test03(self):
        print("test03执行")
&gt;       assert 0
E       assert 0

Scripts\test_allure.py:22: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="critical"/>
        <label name="thread" value="7192-MainThread"/>
        <label name="host" value="DESKTOP-E9B9154"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
